version: "3.5"

services:

  server:
    image: gvenzl/oracle-xe
    platform: linux/amd64
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      - data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    healthcheck:
      test: healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  data:
